### ISSUE TITLE
where is the link 

### ISSUE THREAD

**Issue by Voltern** [edible-wiki/Status#4]

**Comment by duckboycool** [comment]
The link to the what? The status website link is in the top area with the topics and the link to the wiki is in the website at the underlined Edible Wiki.

**Comment by Voltern** [comment]
the ediable wiki

**Comment by duckboycool** [comment]
? "the link to the wiki is in the website at the underlined Edible Wiki."

**Comment by Voltern** [comment]
Nervemind.
